export default {
  MAX: 10,
  JWTTOKEN: "JWTTOKEN",
  REFRESHTOKEN: "REFRESHTOKEN",
  COUNTRIES: "COUNTRIES",
  LOGINUSER: "LOGINUSER",
  COMPANYIES: "COMPANYIES",
  CITIES: "CITIES",
  REGIONS: "REGIONS",
  BRANCHES: "BRANCHES",
  USERS: "USERS",
  USERCOMPANY: 'USERCOMPANY',
  SELECTEDPLAN: 'SELECTEDPLAN',
  VATAMOUNT: 0.15

};